world:
  worldName: IceKart
  spawnHeight: 301.0
game:
  countDownLength: 10
  minPlayers: 2
  startHeight: 250
  endHeight: 230
  deathDistance: 32
  decaySpeed: 0.5
  decayDistance: 4
generation:
  firstPathRadius: 15.0
  pathRadiusStart: 12.0
  pathRadiusEnd: 2.0
  radiusShrink: 0.5
  turnZoneStart: 50.0
  turnZoneEnd: 100.0
  lengthScale: 40.0
items:
  disableCraftingSecret: false
  boxDelay: 45
  boxHeight: 1.6
  boxSpawnRate: 2.0
  levitation:
    name: "Levitation"
    description: "Drop to allow your boat to hover in the air for a short time\nCrouch to cancel early, your XP bar shows the time left"
    startingItems: 4
    boxWeight: 0
    duration: 100
  teleporter:
    name: "Teleporter"
    description: "Drop to teleport back to your last safe position\nThrow to teleport to where it lands"
    startingItems: 5
    boxWeight: 0
  blindness:
    name: "Blindness"
    description: "Drop to create a dark cloud behind you that blinds enemies"
    startingItems: 0
    boxWeight: 1
    lingerDuration: 300
    effectDuration: 40
  melter:
    name: "Track Melter"
    description: "Drop to melt the track behind you"
    startingItems: 0
    boxWeight: 1
    duration: 300
  snow:
    name: "Snowball"
    description: "Drop to create an area of snow behind you\nThrow to create a trail of snow beneath the snowball"
    startingItems: 0
    boxWeight: 1
    dropBackwards: 4
