world:
  worldName: IceKart
  spawnHeight: 301.0
game:
  countDownLength: 10
  minPlayers: 2
  startHeight: 250
  endHeight: 230
  deathDistance: 32
  decaySpeed: 0.5
  decayDistance: 4
generation:
  firstPathRadius: 15.0
  pathRadiusStart: 12.0
  pathRadiusEnd: 2.0
  radiusShrink: 0.5
  turnZoneStart: 50.0
  turnZoneEnd: 100.0
  lengthScale: 40.0
items:
  disableCraftingSecret: false
  levitationItems: 4
  levitationBoxWeight: 0
  levitationDuration: 100
  teleporterItems: 5
  teleporterBoxWeight: 0
  blindnessItems: 0
  blindnessBoxWeight: 1
  blindnessLingerDuration: 300
  blindnessEffectDuration: 40
  melterItems: 0
  melterBoxWeight: 1
  melterDuration: 300
  snowItems: 0
  snowBoxWeight: 1
  snowDropBackwards: 4
  boxDelay: 45
  boxHeight: 1.6
  boxSpawnRate: 2.0
